version: '3.8'

services:
  termreader:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - Auth__Email=${AUTH_EMAIL}
      - Auth__Password=${AUTH_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    # Increase shared memory size to prevent Chrome crashes
    shm_size: '2gb'
    restart: "no"
