// Licensed under the MIT License. See LICENSE in the repository root.

using System.Xml.Linq;
using FluentAssertions;
using WireCopy.Infrastructure.Browser.CommandHandlers;
using Xunit;

namespace WireCopy.Tests.Browser;

/// <summary>
/// Tests for the placeholder RSS feed published after a successful GCS
/// verify probe (workspace-nlq6). The XML is generated by
/// <see cref="PodcastGcsWizard.BuildSelfTestFeedXml"/> — a pure helper so
/// the shape can be tested without a GCS client.
/// </summary>
[Trait("Category", "Unit")]
public class SelfTestFeedXmlTests
{
    private static readonly DateTime FixedTime =
        new(2026, 5, 14, 19, 30, 45, DateTimeKind.Utc);

    [Fact]
    public void BuildSelfTestFeedXml_IsValidXml()
    {
        var xml = PodcastGcsWizard.BuildSelfTestFeedXml("my-test-bucket", FixedTime);
        var act = () => XDocument.Parse(xml);
        act.Should().NotThrow();
    }

    [Fact]
    public void BuildSelfTestFeedXml_HasRssChannel()
    {
        var xml = PodcastGcsWizard.BuildSelfTestFeedXml("my-test-bucket", FixedTime);
        var doc = XDocument.Parse(xml);
        doc.Root.Should().NotBeNull();
        doc.Root!.Name.LocalName.Should().Be("rss");
        doc.Root.Element("channel").Should().NotBeNull();
    }

    [Fact]
    public void BuildSelfTestFeedXml_EmbedsBucketLink()
    {
        var xml = PodcastGcsWizard.BuildSelfTestFeedXml("acme-podcasts-prod", FixedTime);
        var doc = XDocument.Parse(xml);
        var link = doc.Root!.Element("channel")!.Element("link")!.Value;
        link.Should().Be("https://storage.googleapis.com/acme-podcasts-prod/feed.xml");
    }

    [Fact]
    public void BuildSelfTestFeedXml_LastBuildDate_IsRfc822Format()
    {
        var xml = PodcastGcsWizard.BuildSelfTestFeedXml("my-bucket", FixedTime);
        var doc = XDocument.Parse(xml);
        var date = doc.Root!.Element("channel")!.Element("lastBuildDate")!.Value;
        date.Should().Be("Thu, 14 May 2026 19:30:45 +0000");
    }

    [Fact]
    public void BuildSelfTestFeedXml_DescriptionMentionsPlaceholder()
    {
        var xml = PodcastGcsWizard.BuildSelfTestFeedXml("my-bucket", FixedTime);
        var doc = XDocument.Parse(xml);
        var desc = doc.Root!.Element("channel")!.Element("description")!.Value;
        desc.Should().Contain("Placeholder");
        desc.Should().Contain("WireCopy verify");
    }

    [Fact]
    public void BuildSelfTestFeedXml_HandlesUnderscoreBucketNames()
    {
        // workspace-wooa: underscores are valid in bucket names.
        var xml = PodcastGcsWizard.BuildSelfTestFeedXml("tr_list_reader", FixedTime);
        var doc = XDocument.Parse(xml);
        var link = doc.Root!.Element("channel")!.Element("link")!.Value;
        link.Should().Be("https://storage.googleapis.com/tr_list_reader/feed.xml");
    }
}
